version: '3.8'

services:
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payments
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: root

    ports:
      - "3306:3306"

    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
